<script setup>
import { onMounted, reactive, ref } from 'vue'
import { useRoute, useRouter } from 'vue-router'
import { useToast } from 'primevue/usetoast'
import Card from 'primevue/card'
import Select from 'primevue/select'
import Tag from 'primevue/tag'
import AppButton from '@/components/common/AppButton.vue'
import { getComplaint, updateComplaintStatus, uploadComplaintAttachment } from '@/services/complaint.service'
import { getListCache, updateListCache } from '@/services/list-cache'
const route = useRoute(); const router = useRouter(); const toast = useToast(); const cachedComplaint = getListCache('complaints')?.find((item) => item.complaint_id === Number(route.params.id)); const loading = ref(!cachedComplaint); const saving = ref(false); const uploading = ref(false); const selectedFile = ref(null)
const complaint = reactive({ complaint_id: null, status: 'Submitted', category: '', title: '', description: '', submitted_at: '', citizen: {}, attachments: [], ...cachedComplaint }); const selectedStatus = ref(cachedComplaint?.status ?? 'Submitted')
const statusOptions = [{ label: 'Menunggu Verifikasi', value: 'Submitted' }, { label: 'Sedang Diproses', value: 'In Progress' }, { label: 'Selesai', value: 'Resolved' }, { label: 'Ditolak', value: 'Rejected' }]
const statusLabel = { Submitted: 'Menunggu Verifikasi', 'In Progress': 'Sedang Diproses', Resolved: 'Selesai', Rejected: 'Ditolak' }
function messageFrom(error, fallback) { return error.response?.data?.message ?? fallback }
async function loadComplaint({ background = false } = {}) { if (!background) loading.value = true; try { Object.assign(complaint, await getComplaint(route.params.id)); selectedStatus.value = complaint.status } catch (error) { toast.add({ severity: 'error', summary: 'Gagal memuat pengaduan', detail: messageFrom(error, 'Coba lagi.'), life: 3500 }) } finally { if (!background) loading.value = false } }
function chooseFile(event) { selectedFile.value = event.target.files?.[0] ?? null }
async function uploadFile() { if (!selectedFile.value) return; uploading.value = true; try { const attachment = await uploadComplaintAttachment(complaint.complaint_id, selectedFile.value); complaint.attachments.push(attachment); selectedFile.value = null; toast.add({ severity: 'success', summary: 'Lampiran berhasil diunggah', life: 2500 }) } catch (error) { toast.add({ severity: 'error', summary: 'Upload lampiran gagal', detail: messageFrom(error, 'Coba lagi.'), life: 3500 }) } finally { uploading.value = false } }
async function handleSave() { saving.value = true; try { const result = await updateComplaintStatus(complaint.complaint_id, { status: selectedStatus.value }); complaint.status = result.complaint?.status ?? selectedStatus.value; updateListCache('complaints', items => items.map(item => item.complaint_id === complaint.complaint_id ? { ...item, status: complaint.status } : item)); toast.add({ severity: 'success', summary: 'Status pengaduan diperbarui', life: 2500 }) } catch (error) { toast.add({ severity: 'error', summary: 'Gagal memperbarui status', detail: messageFrom(error, 'Coba lagi.'), life: 3500 }) } finally { saving.value = false } }
onMounted(() => loadComplaint({ background: Boolean(cachedComplaint) }))
</script>
<template><div class="grid grid-cols-1 lg:grid-cols-[1fr_320px] gap-5"><div class="flex flex-col gap-5"><div><h1 class="text-2xl font-bold text-gray-800 m-0">Detail Aduan #{{ complaint.complaint_id }}</h1><p class="text-sm text-gray-500">Dibuat pada {{ complaint.submitted_at }}</p></div><Card><template #content><h2 class="font-semibold mb-4">Informasi Pelapor</h2><p>Nama: {{ complaint.citizen?.full_name ?? '-' }}</p><p>NIK: {{ complaint.citizen?.national_id ?? '-' }}</p><p>Telepon: {{ complaint.citizen?.phone_number ?? '-' }}</p><p>Alamat: {{ complaint.citizen?.address ?? '-' }}</p></template></Card><Card><template #content><h2 class="font-semibold mb-4">{{ complaint.title }}</h2><Tag :value="complaint.category" severity="secondary" /><p class="mt-4">{{ complaint.description }}</p><h3 class="font-semibold mt-5 mb-2">Lampiran</h3><div v-if="complaint.attachments?.length" class="space-y-2"><a v-for="file in complaint.attachments" :key="file.attachment_id" :href="file.file_path" target="_blank" class="block text-primary-700 underline">{{ file.file_name }}</a></div><p v-else class="text-sm text-gray-400">Belum ada lampiran.</p><div class="flex items-center gap-2 mt-4"><input type="file" accept="image/*,.pdf" @change="chooseFile" /><AppButton label="Upload" variant="secondary" :loading="uploading" :disabled="!selectedFile" @click="uploadFile" /></div></template></Card></div><Card><template #content><h2 class="font-semibold mb-4">Status &amp; Tindakan</h2><Tag :value="statusLabel[complaint.status] ?? complaint.status" severity="info" class="mb-3" /><Select v-model="selectedStatus" :options="statusOptions" option-label="label" option-value="value" class="w-full mb-3" /><AppButton label="Simpan Perubahan" variant="primary" class="w-full" :loading="saving" @click="handleSave" /><AppButton label="Kembali" variant="secondary" outlined class="w-full mt-2" @click="router.push({ name: 'complaint-list' })" /></template></Card></div></template>
